server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/geodesgemstones
    username: root
    driver-class-name: com.mysql.jdbc.Driver
