server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/geodesgemstones
    username: root
    driver-class-name: com.mysql.jdbc.Driver

twitter:
  oauth:
    appid: 3Butd2tOyM9pNoQqMA321U1zL
    appsecret: N076uOlEKakKTjfQaOvtnsw3JexjFeQHWygui5BsZhckY6WQ3D
    accesstoken: 895126013352345600-y4l3PsdtMMAQHLnDg95tfRHDKWlnXs4
    accesssecret: uJHMHRlMy4Vuze2OLrgT5EACxCOifW05gS9vga5Pzv9vg

security:
  username: user
  password: password

features:
  social-media:
    enabled: true

imgur:
  endpoint:
    imageupload: https://api.imgur.com/3/image
  clientid: 7872643312136fd
  clientsecret: 268fe7d55070da46e5863714ae45dc2c299716d7