server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net:3306/heroku_cdf390c6cfbd684
    username: b104ce1dfd148f
    password: 9a0f751e
    driver-class-name: com.mysql.jdbc.Driver

twitter:
  oauth:
    appid: 3Butd2tOyM9pNoQqMA321U1zL
    appsecret: N076uOlEKakKTjfQaOvtnsw3JexjFeQHWygui5BsZhckY6WQ3D
    accesstoken: 895126013352345600-y4l3PsdtMMAQHLnDg95tfRHDKWlnXs4
    accesssecret: uJHMHRlMy4Vuze2OLrgT5EACxCOifW05gS9vga5Pzv9vg

security:
  username: user
  password: password

features:
  social-media:
    enabled: true

imgur:
  endpoint:
    imageupload: https://api.imgur.com/3/image
  clientid: ed138f9ce6b3305
  clientsecret: 0e3a03398161ae6e4dba3546804037ccc1cb60ed